# Lecture notes

in chronological order, with slies and the code that produced the slides (that I run in class):

| Section | Slides | PDF | Code |
|:---------------------------|:--------|:--------------|:----------|
|STAC33 course outline | [Slides](http://ritsokiguess.site/lecture-notes/outline_c33.html) | [PDF](http://ritsokiguess.site/lecture-notes/outline_c33.pdf) | [Code](http://ritsokiguess.site/lecture-notes/outline_c33.qmd) |
|Running R | [Slides](http://ritsokiguess.site/lecture-notes/running.html) | [PDF](http://ritsokiguess.site/lecture-notes/running.pdf) | [Code](http://ritsokiguess.site/lecture-notes/running.qmd) |
|Reading data files | [Slides](http://ritsokiguess.site/lecture-notes/readfile.html) | [PDF](http://ritsokiguess.site/lecture-notes/readfile.pdf) | [Code](http://ritsokiguess.site/lecture-notes/readfile.qmd) |
|Drawing graphs | [Slides](http://ritsokiguess.site/lecture-notes/graphs.html) | [PDF](http://ritsokiguess.site/lecture-notes/graphs.pdf) | [Code](http://ritsokiguess.site/lecture-notes/graphs.qmd) |
|Numerical summaries | [Slides](http://ritsokiguess.site/lecture-notes/numsum.html) | [PDF](http://ritsokiguess.site/lecture-notes/numsum.pdf) | [Code](http://ritsokiguess.site/lecture-notes/numsum.qmd) |
|Choosing things from dataframes| [Slides](http://ritsokiguess.site/lecture-notes/choosing.html) | [PDF](http://ritsokiguess.site/lecture-notes/choosing.pdf) | [Code](http://ritsokiguess.site/lecture-notes/choosing.qmd) |
|Inference: one and two-sample t | [Slides](http://ritsokiguess.site/lecture-notes/inference_1.html) | [PDF](http://ritsokiguess.site/lecture-notes/inference_1.pdf) | [Code](http://ritsokiguess.site/lecture-notes/inference_1.qmd) | 
|Bootstrap for sample mean | [Slides](http://ritsokiguess.site/lecture-notes/bootstrap_R.html) | [PDF](http://ritsokiguess.site/lecture-notes/bootstrap_R.pdf) | [Code](http://ritsokiguess.site/lecture-notes/bootstrap_R.qmd) |
|Inference: power | [Slides](http://ritsokiguess.site/lecture-notes/inference_2.html) | [PDF](http://ritsokiguess.site/lecture-notes/inference_2.pdf) | [Code](http://ritsokiguess.site/lecture-notes/inference_2.qmd) |
|Inference: sign test | [Slides](http://ritsokiguess.site/lecture-notes/inference_3.html) | [PDF](http://ritsokiguess.site/lecture-notes/inference_3.pdf) | [Code](http://ritsokiguess.site/lecture-notes/inference_3.qmd) |
|Inference: normal quantile plot | [Slides](http://ritsokiguess.site/lecture-notes/inference_4a.html) | [PDF](http://ritsokiguess.site/lecture-notes/inference_4a.pdf) | [Code](http://ritsokiguess.site/lecture-notes/inference_4a.qmd) |
|Inference: matched pairs | [Slides](http://ritsokiguess.site/lecture-notes/inference_4b.html) | [PDF](http://ritsokiguess.site/lecture-notes/inference_4b.pdf) | [Code](http://ritsokiguess.site/lecture-notes/inference_4b.qmd) |
|Inference: Mood's median test | [Slides](http://ritsokiguess.site/lecture-notes/inference_5a.html) | [PDF](http://ritsokiguess.site/lecture-notes/inference_5a.pdf) | [Code](http://ritsokiguess.site/lecture-notes/inference_5a.qmd) |
|Inference: analysis of variance | [Slides](http://ritsokiguess.site/lecture-notes/inference_5b.html) | [PDF](http://ritsokiguess.site/lecture-notes/inference_5b.pdf) | [Code](http://ritsokiguess.site/lecture-notes/inference_5b.qmd) |
|Writing reports | [Slides](http://ritsokiguess.site/lecture-notes/reports.html) |[PDF](http://ritsokiguess.site/lecture-notes/reports.pdf) |[Code](http://ritsokiguess.site/lecture-notes/reports.qmd) |
|Tidying data | [Slides](http://ritsokiguess.site/lecture-notes/tidying.html) | [PDF](http://ritsokiguess.site/lecture-notes/tidying.pdf) | [Code](http://ritsokiguess.site/lecture-notes/tidying.qmd) |
|Tidying data: extras | [Slides](http://ritsokiguess.site/lecture-notes/tidy_extra.html) | [PDF](http://ritsokiguess.site/lecture-notes/tidy_extra.pdf) | [Code](http://ritsokiguess.site/lecture-notes/tidy_extra.qmd) |
|When `pivot_wider` goes wrong | [Slides](http://ritsokiguess.site/lecture-notes/wider_wrong.html) | [PDF](http://ritsokiguess.site/lecture-notes/wider_wrong.pdf) | [Code](http://ritsokiguess.site/lecture-notes/wider_wrong.qmd) |
|Case study: windmill | [Slides](http://ritsokiguess.site/lecture-notes/windmill.html) | [PDF](http://ritsokiguess.site/lecture-notes/windmill.pdf) | [Code](http://ritsokiguess.site/lecture-notes/windmill.qmd) |
|Case study: asphalt | [Slides](http://ritsokiguess.site/lecture-notes/asphalt.html) | [PDF](http://ritsokiguess.site/lecture-notes/asphalt.pdf) | [Code](http://ritsokiguess.site/lecture-notes/asphalt.qmd) |
|Regression with categorical variables | [Slides](http://ritsokiguess.site/lecture-notes/with_categ.html) | [PDF](http://ritsokiguess.site/lecture-notes/with_categ.pdf) | [Code](http://ritsokiguess.site/lecture-notes/with_categ.qmd) |
|Functions | [Slides](http://ritsokiguess.site/lecture-notes/functions.html) | [PDF](http://ritsokiguess.site/lecture-notes/functions.pdf) | [Code](http://ritsokiguess.site/lecture-notes/functions.qmd) |
|Vector and matrix algebra | [Slides](http://ritsokiguess.site/lecture-notes/vector_matrix.html) | [PDF](http://ritsokiguess.site/lecture-notes/vector_matrix.pdf) |  [Code](http://ritsokiguess.site/lecture-notes/vector_matrix.qmd) |
|Bootstrap revisited | [Slides](http://ritsokiguess.site/lecture-notes/bootstrap.html) | [PDF](http://ritsokiguess.site/lecture-notes/bootstrap.pdf) | [Code](http://ritsokiguess.site/lecture-notes/bootstrap.qmd) |
|Bayesian statistics with Stan | [Slides](http://ritsokiguess.site/lecture-notes/rstan.html) | [PDF](http://ritsokiguess.site/lecture-notes/rstan.pdf) | [Code](http://ritsokiguess.site/lecture-notes/rstan.qmd) |
