---
title: "Old exams"
---

- This course is relatively new, and the old exams don't go back very far. If you want more practice, especially for midterms, you can try the [STAC32 old exam page](https://ritsokiguess.site/STAC32/old_exams.html).

- My exams come with a booklet of questions (with space to write your answers). In the exam, there are references to Figures which are in a separate booklet (in the column Figures below). Print that out, or otherwise have it available as you work through each exam. 
- Here are the old midterm and final exams that I have. You will notice that the best way of doing things *has changed over time*. Be guided by how things are done now rather than in the past.
- One of the *most effective* ways to find out whether you know something is to answer questions on it. (Another way is to explain it to someone else.) Thus, your best use of these exams is to *do them under exam conditions* without looking at the solutions, and *then* look at the solutions and grade yourself. This is the fastest way to find out what you don't understand. Read through your notes and work through examples on what you missed, then tackle another exam.
- If all you do is read through the solutions, you have *wasted a huge learning opportunity*, because you will not be prepared to deal with what you face on exam day.

## Old midterm exams

Year  | Exam                          | Figures                         | Solutions
:-----|:------------------------------|:--------------------------------|:-------------------------------------------
2019 | [exam](midterm-20201-q.pdf)  | [figures](midterm-20201-f.pdf)   | [solutions](midterm-20201-s.pdf) |
2022  | [exam](midterm-20221-c33.pdf) | needs sorting out               |
2023  | [exam](midterm-20231-c33.pdf) | needs sorting out               |


In 2021 the course was online with no exams; in 2022, the course was partly online, with an online assignment-like midterm. I actually think the course was first run in 2020, but the exam is dated 2019, so we'll go with that. (I remember the midterm in 2020 happening just before COVID did.)
 
## Old final exams

Year  | Exam                       | Figures                       | Solutions
:-----|:---------------------------|:------------------------------|:------------------------------------------
2022  | [exam](final-20221-q.pdf)  | [figures](final-20221-f.pdf)  | [solutions](final-20221-s.pdf)
2023  | [exam](final-20231-c33.pdf)| needs sorting out

