---
title: "Lecture notes"
format: html
---

Here are my lecture notes, all of them, in chronological order, with the slideshows, PDF versions of those (for printing) and the Quarto documents with the code that made the slides:

| Section | Slides | PDF | Code |
|:--------|:--------|:--------------|:----------|
|STAC32 course outline | [Slides](http://ritsokiguess.site/lecture-notes/outline_c32.html) | [PDF](https://raw.githubusercontent.com/nxskok/lecture-notes/master/outline_c32.pdf) | [Code](https://raw.githubusercontent.com/nxskok/lecture-notes/master/outline_c32.qmd) |
|Running R | [Slides](http://ritsokiguess.site/lecture-notes/running.html) | [PDF](https://raw.githubusercontent.com/nxskok/lecture-notes/master/running.pdf) | [Code](https://raw.githubusercontent.com/nxskok/lecture-notes/master/running.qmd) |
|Reading data files | [Slides](http://ritsokiguess.site/lecture-notes/readfile.html) | [PDF](https://raw.githubusercontent.com/nxskok/lecture-notes/master/readfile.pdf) | [Code](https://raw.githubusercontent.com/nxskok/lecture-notes/master/readfile.qmd) |
|Drawing graphs | [Slides](http://ritsokiguess.site/lecture-notes/graphs.html) | [PDF](https://raw.githubusercontent.com/nxskok/lecture-notes/master/graphs.pdf) | [Code](https://raw.githubusercontent.com/nxskok/lecture-notes/master/graphs.qmd) |
|Numerical summaries | [Slides](http://ritsokiguess.site/lecture-notes/numsum.html) | [PDF](https://raw.githubusercontent.com/nxskok/lecture-notes/master/numsum.pdf) | [Code](https://raw.githubusercontent.com/nxskok/lecture-notes/master/numsum.qmd) |
|Choosing things from dataframes| [Slides](http://ritsokiguess.site/lecture-notes/choosing.html) | [PDF](https://raw.githubusercontent.com/nxskok/lecture-notes/master/choosing.pdf) | [Code](https://raw.githubusercontent.com/nxskok/lecture-notes/master/choosing.qmd) |
|Inference: one and two-sample t | [Slides](http://ritsokiguess.site/lecture-notes/inference_1.html) | [PDF](https://raw.githubusercontent.com/nxskok/lecture-notes/master/inference_1.pdf) | [Code](https://raw.githubusercontent.com/nxskok/lecture-notes/master/inference_1.qmd) | 
|Bootstrap for sample mean | [Slides](http://ritsokiguess.site/lecture-notes/bootstrap_R.html) | [PDF](https://raw.githubusercontent.com/nxskok/lecture-notes/master/bootstrap_R.pdf) | [Code](https://raw.githubusercontent.com/nxskok/lecture-notes/master/bootstrap_R.qmd) |
|Inference: power | [Slides](http://ritsokiguess.site/lecture-notes/inference_2.html) | [PDF](https://raw.githubusercontent.com/nxskok/lecture-notes/master/inference_2.pdf) | [Code](https://raw.githubusercontent.com/nxskok/lecture-notes/master/inference_2.qmd) |
|Inference: sign test | [Slides](http://ritsokiguess.site/lecture-notes/inference_3.html) | [PDF](https://raw.githubusercontent.com/nxskok/lecture-notes/master/inference_3.pdf) | [Code](https://raw.githubusercontent.com/nxskok/lecture-notes/master/inference_3.qmd) |
|Inference: normal quantile plot | [Slides](http://ritsokiguess.site/lecture-notes/inference_4a.html) | [PDF](https://raw.githubusercontent.com/nxskok/lecture-notes/master/inference_4a.pdf) | [Code](https://raw.githubusercontent.com/nxskok/lecture-notes/master/inference_4a.qmd) |
|Inference: matched pairs | [Slides](http://ritsokiguess.site/lecture-notes/inference_4b.html) | [PDF](https://raw.githubusercontent.com/nxskok/lecture-notes/master/inference_4b.pdf) | [Code](https://raw.githubusercontent.com/nxskok/lecture-notes/master/inference_4b.qmd) |
|Inference: Mood's median test | [Slides](http://ritsokiguess.site/lecture-notes/inference_5a.html) | [PDF](https://raw.githubusercontent.com/nxskok/lecture-notes/master/inference_5a.pdf) | [Code](https://raw.githubusercontent.com/nxskok/lecture-notes/master/inference_5a.qmd) |
|Inference: analysis of variance | [Slides](http://ritsokiguess.site/lecture-notes/inference_5b.html) | [PDF](https://raw.githubusercontent.com/nxskok/lecture-notes/master/inference_5b.pdf) | [Code](https://raw.githubusercontent.com/nxskok/lecture-notes/master/inference_5b.qmd) |
|Writing reports | [Slides](http://ritsokiguess.site/lecture-notes/reports.html) |[PDF](https://raw.githubusercontent.com/nxskok/lecture-notes/master/reports.pdf) |[Code](https://raw.githubusercontent.com/nxskok/lecture-notes/master/reports.qmd) |
|Tidying data | [Slides](http://ritsokiguess.site/lecture-notes/tidying.html) | [PDF](https://raw.githubusercontent.com/nxskok/lecture-notes/master/tidying.pdf) | [Code](https://raw.githubusercontent.com/nxskok/lecture-notes/master/tidying.qmd) |
|Tidying data: extras | [Slides](http://ritsokiguess.site/lecture-notes/tidy_extra.html) | [PDF](https://raw.githubusercontent.com/nxskok/lecture-notes/master/tidy_extra.pdf) | [Code](https://raw.githubusercontent.com/nxskok/lecture-notes/master/tidy_extra.qmd) |
|When `pivot_wider` goes wrong | [Slides](http://ritsokiguess.site/lecture-notes/wider_wrong.html) | [PDF](https://raw.githubusercontent.com/nxskok/lecture-notes/master/wider_wrong.pdf) | [Code](https://raw.githubusercontent.com/nxskok/lecture-notes/master/wider_wrong.qmd) |
|Case study: windmill | [Slides](http://ritsokiguess.site/lecture-notes/windmill.html) | [PDF](https://raw.githubusercontent.com/nxskok/lecture-notes/master/windmill.pdf) | [Code](https://raw.githubusercontent.com/nxskok/lecture-notes/master/windmill.qmd) |
|Case study: asphalt | [Slides](http://ritsokiguess.site/lecture-notes/asphalt.html) | [PDF](https://raw.githubusercontent.com/nxskok/lecture-notes/master/asphalt.pdf) | [Code](https://raw.githubusercontent.com/nxskok/lecture-notes/master/asphalt.qmd) |
|Regression with categorical variables | [Slides](http://ritsokiguess.site/lecture-notes/with_categ.html) | [PDF](https://raw.githubusercontent.com/nxskok/lecture-notes/master/with_categ.pdf) | [Code](https://raw.githubusercontent.com/nxskok/lecture-notes/master/with_categ.qmd) |
|Functions | [Slides](http://ritsokiguess.site/lecture-notes/functions.html) | [PDF](https://raw.githubusercontent.com/nxskok/lecture-notes/master/functions.pdf) | [Code](https://raw.githubusercontent.com/nxskok/lecture-notes/master/functions.qmd) |
|Dates and Times | [Slides](http://ritsokiguess.site/lecture-notes/dates_and_times.html) | [PDF](https://raw.githubusercontent.com/nxskok/lecture-notes/master/dates_and_times.pdf) | [Code](https://raw.githubusercontent.com/nxskok/lecture-notes/master/dates_and_times.qmd) |
|Durations, intervals and periods | [Slides](http://ritsokiguess.site/lecture-notes/dip.html) | [PDF](https://raw.githubusercontent.com/nxskok/lecture-notes/master/dip.pdf) | [Code](https://raw.githubusercontent.com/nxskok/lecture-notes/master/dip.qmd) |






